# permissions for end users to view grouptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grouptemplate-viewer-role
rules:
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates/status
  verbs:
  - get
