# permissions for end users to edit grouptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grouptemplate-editor-role
rules:
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates/status
  verbs:
  - get
