# permissions for end users to view groupsyncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupsyncer-viewer-role
rules:
- apiGroups:
  - okta.github.com
  resources:
  - groupsyncers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - okta.github.com
  resources:
  - groupsyncers/status
  verbs:
  - get
