---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates/finalizers
  verbs:
  - update
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates/status
  verbs:
  - get
  - patch
  - update
