---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "okta-user-controller.fullname" . }}-env
  labels:
    {{- include "okta-user-controller.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}