{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  {{- with .Values.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
metadata:
  name: {{ include "okta-user-controller.serviceAccountName" . }}
  labels:
    {{- include "okta-user-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.imagePullSecrets }}
  {{- end }}
{{- end }}