apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "okta-user-controller.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "okta-user-controller.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "okta-user-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}