---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "okta-user-controller.fullname" . }}-manager-role
rules:
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates/finalizers
  verbs:
  - update
- apiGroups:
  - okta.github.com
  resources:
  - grouptemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete